[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino

board_build.partitions = min_spiffs.csv

upload_speed = 460800
monitor_speed = 115200

lib_deps = 
    esphome/ESPAsyncWebServer-esphome @ ^3.4.0
    esphome/AsyncTCP-esphome @ 2.1.4
    vshymanskyy/StreamDebugger @ ^1.0.1
    bblanchon/ArduinoJson @ ^7
    arduino-libraries/NTPClient@ ^3.2.1
    knolleary/PubSubClient@ ^2.8
    4-20ma/ModbusMaster@ ^2.0.1
    ayushsharma82/ElegantOTA@ ^3.1.6

lib_ignore = ESPAsyncWebServer